**Loading the MNIST dataset in Keras**

In [52]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [53]:
train_images.shape

(60000, 28, 28)

In [54]:
len(train_labels)

60000

In [55]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [56]:
test_images.shape

(10000, 28, 28)

In [57]:
len(test_labels)

10000

In [58]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**The network architecture**

In [59]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

**The compilation step**

In [60]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

**Preparing the image data**

In [61]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

**"Fitting" the model**

In [62]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 2s 4ms/step - loss: 0.2554 - accuracy: 0.9259
Epoch 2/5
469/469 [==============================] - 2s 4ms/step - loss: 0.1031 - accuracy: 0.9697
Epoch 3/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0687 - accuracy: 0.9793
Epoch 4/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0494 - accuracy: 0.9850
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0378 - accuracy: 0.9886


**Using the model to make predictions**

In [63]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 26ms/step


array([1.7467318e-08, 4.4513098e-11, 2.9442881e-06, 4.6401354e-05,
       5.6207128e-13, 2.4515968e-08, 4.5505392e-14, 9.9995029e-01,
       1.0706297e-07, 2.4334477e-07], dtype=float32)

In [64]:
predictions[0].argmax()

7

In [65]:
predictions[0][7]

0.9999503

In [66]:
test_labels[0]

7

**Evaluating the model on new data**

In [67]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 0s 906us/step - loss: 0.0642 - accuracy: 0.9807
test_acc: 0.9807000160217285
